/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import model.Camera;
import service.CameraService;

/**
 *
 * @author Dell
 */
public class CameraTruocView extends javax.swing.JFrame {

    private List<Camera> list = new ArrayList<>();
    private CameraService cameraService = new CameraService();
    private DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form CmeraTruocView
     */
    public CameraTruocView() {
        initComponents();
        list = cameraService.getAllCameraTruocTheoTuMoiDenCu(0);
        tableModel = (DefaultTableModel) tblCaneratruoc.getModel();
        showData(list);
        btnKhoiPhuc.setEnabled(false);
    }

    //-----------------------------------
    private void showData(List<Camera> lists) {
        tableModel.setRowCount(0);
        for (Camera bn : lists) {
            tableModel.addRow(new Object[]{bn.getId(), bn.getSoluong(), bn.getThongsokithuat() + "MP", bn.getTrangthai() == 1 ? "Không hoạt động" : "Đang hoạt đông"});
        }
    }
    //----------------------------------------

    private Camera getForm() {
        Camera cm = new Camera(0, Integer.parseInt(txtSoluong.getText().trim().trim()), 0, Integer.parseInt(txtThongSoKithuat.getText().trim().trim()), 0, null, null);
        return cm;
    }
    //-----------------------------------------------------

    private void showIndex(int viTri) {
        Camera bn = list.get(viTri);
        txtSoluong.setText(bn.getSoluong() + "");
        txtThongSoKithuat.setText(bn.getThongsokithuat() + "");
        int trangThai = bn.getTrangthai();
//          if(trangThai == 1){
//              cbbTrangThai.setSelectedIndex(0);
//          }else{
//              cbbTrangThai.setSelectedIndex(1);
//          }
//         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        txtThongSoKithuat = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhoiPhuc = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaneratruoc = new javax.swing.JTable();
        cbbTrangThai = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Số lượng");

        jLabel2.setText("Thông số kĩ thuật");

        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnKhoiPhuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhoiPhuc.setText("Khôi Phục");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        btnX.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnKhoiPhuc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnX))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                    .addComponent(txtThongSoKithuat)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCapnhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtThongSoKithuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapnhat)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoiPhuc)
                    .addComponent(btnX))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblCaneratruoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Số Lượng", "Thông Số", "Trạng Thái"
            }
        ));
        tblCaneratruoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCaneratruocMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblCaneratruocMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblCaneratruoc);

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Không hoạt động" }));
        cbbTrangThai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbTrangThaiMouseClicked(evt);
            }
        });
        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(cbbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCaneratruoc.getSelectedRow();
            cameraService.deleteCamera(list.get(row).getId());
            list = cameraService.getAllCameraTruoc();
            showData(list);
            txtSoluong.setText("");
            txtThongSoKithuat.setText("");
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
    }//GEN-LAST:event_btnXActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:

        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCaneratruoc.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng trong bảng để cập nhật");
            } else {
                String soLuongStr = txtSoluong.getText().trim().trim().trim();
                String thongSoKTStr = txtThongSoKithuat.getText().trim().trim().trim();

                if (soLuongStr.equals("") || thongSoKTStr.equals("")) {
                    JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật không được bỏ trống");
                } else {
                    try {
                        int soLuong = Integer.parseInt(soLuongStr);
                        int thongSoKT = Integer.parseInt(thongSoKTStr);

                        if (soLuong <= 0 || soLuong >= 31 || thongSoKT <= 0 || thongSoKT >= 31) {
                            JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải nằm trong khoảng từ 1 đến 30");
                        } else {
                            cameraService.sua(getForm(), list.get(row).getId());
                            list = cameraService.getAllCameraTruocTheoTuMoiDenCu(0);
                            showData(list);
                            txtSoluong.setText("");
                            txtThongSoKithuat.setText("");
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải là số nguyên");
                    }
                }
            }
        }

    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:

        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            String soLuongStr = txtSoluong.getText().trim().trim().trim();
            String thongSoKTStr = txtThongSoKithuat.getText().trim().trim().trim();

            if (soLuongStr.equals("") || thongSoKTStr.equals("")) {
                JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật không được bỏ trống");
            } else {
                try {
                    int soLuong = Integer.parseInt(soLuongStr);
                    int thongSoKT = Integer.parseInt(thongSoKTStr);

                    if (soLuong <= 0 || soLuong >= 31 || thongSoKT <= 0 || thongSoKT >= 31) {
                        JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải nằm trong khoảng từ 1 đến 30");
                    } else {
                        cameraService.addCameraTruoc(getForm());
                        list = cameraService.getAllCameraTruocTheoTuMoiDenCu(0);
                        showData(list);
                        txtSoluong.setText("");
                        txtThongSoKithuat.setText("");
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải là số nguyên");
                }
            }
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void tblCaneratruocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCaneratruocMouseClicked
//        // TODO add your handling code here:
        int row = tblCaneratruoc.getSelectedRow();
        showIndex(row);

    }//GEN-LAST:event_tblCaneratruocMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCaneratruoc.getSelectedRow();
            cameraService.dungHoatDongCameraTheoID(list.get(row).getId());
            cbbTrangThai.setSelectedIndex(0);
            list = cameraService.getAllCameraTruocTheoTuMoiDenCu(0);
            showData(list);
            txtSoluong.setText("");
            txtThongSoKithuat.setText("");
            JOptionPane.showMessageDialog(this, "xóa  thành công");

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Khôi Phục ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCaneratruoc.getSelectedRow();
            cameraService.khoiPhucCameraTheoID(list.get(row).getId());

            cbbTrangThai.setSelectedIndex(1);
            list = cameraService.getAllCameraTruocTheoTuMoiDenCu(1);
            showData(list);
            txtSoluong.setText("");
            txtThongSoKithuat.setText("");
            JOptionPane.showMessageDialog(this, "khôi phục  thành công");
    }//GEN-LAST:event_btnKhoiPhucActionPerformed
    }
    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
        int a = cbbTrangThai.getSelectedIndex();
        list = cameraService.getAllCameraTruocTheoTuMoiDenCu(a);
        showData(list);

        if (a == 0) {

            list = cameraService.getAllCameraTruocTheoTuMoiDenCu(0);

            btnKhoiPhuc.setEnabled(false);
            btnCapnhat.setEnabled(true);
            btnXoa.setEnabled(true);
            showData(list);

        } else if (a == 1) {
            list = cameraService.getAllCameraTruocTheoTuMoiDenCu(1);
            btnCapnhat.setEnabled(false);
            btnXoa.setEnabled(false);
            btnKhoiPhuc.setEnabled(true);
            showData(list);
        }
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    private void cbbTrangThaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbTrangThaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTrangThaiMouseClicked

    private void tblCaneratruocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCaneratruocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCaneratruocMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraTruocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraTruocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraTruocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraTruocView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraTruocView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCaneratruoc;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtThongSoKithuat;
    // End of variables declaration//GEN-END:variables
}
