/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Camera;

import service.CameraService;

/**
 *
 * @author Dell
 */
public class CameraSauView extends javax.swing.JFrame {

    private List<Camera> list = new ArrayList<>();
    private CameraService CameraService = new CameraService();
    private DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form CameraSauView
     */
    public CameraSauView() {
        initComponents();
        list = CameraService.getAllCameraSauTheoTuMoiDenCu(0);
        tableModel = (DefaultTableModel) tblCameraSau.getModel();
        showData(list);
        btnKhoiphuc.setEnabled(false);
    }
//--------------------------------------

    private void showData(List<Camera> lists) {
        tableModel.setRowCount(0);
        for (Camera bn : lists) {
            tableModel.addRow(new Object[]{bn.getId(), bn.getSoluong(), bn.getThongsokithuat() + "MP", bn.getTrangthai() == 1 ? "Không hoạt động" : "Đang hoạt đông"});
        }
    }

    //------------------------------------
    private Camera getForm() {        
        Camera cms = new Camera(0, Integer.parseInt(txtSoluong.getText().trim().trim()), 0, Integer.parseInt(txtThognsokithuat.getText().trim().trim()), 0, null, null);
        return cms;        
    }
    //------------------------------------

    private void showIndex(int vitri) {
        Camera bn = list.get(vitri);
        
        txtSoluong.setText(bn.getSoluong() + "");
        txtThognsokithuat.setText(bn.getThongsokithuat() + "");
        int trangThai = bn.getTrangthai();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        txtThognsokithuat = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhoiphuc = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbbTrangthai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCameraSau = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Số Lượng");

        jLabel2.setText("Thông Số Kĩ Thuật");

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapnhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapnhat.setText("Cập Nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnKhoiphuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhoiphuc.setText("Khôi Phục");
        btnKhoiphuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiphucActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapnhat)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoa))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnKhoiphuc)
                            .addGap(206, 206, 206)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSoluong)
                                .addComponent(txtThognsokithuat, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtThognsokithuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapnhat)
                    .addComponent(btnXoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoiphuc)
                    .addComponent(jButton1))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbbTrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Không hoạt động" }));
        cbbTrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangthaiActionPerformed(evt);
            }
        });

        tblCameraSau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Số Lượng", "Thông Số", "Trạng Thái"
            }
        ));
        tblCameraSau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCameraSauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCameraSau);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(cbbTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:

        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            String soLuongStr = txtSoluong.getText().trim().trim();
            String thongSoKTStr = txtThognsokithuat.getText().trim().trim();
            
            if (soLuongStr.equals("") || thongSoKTStr.equals("")) {
                JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật không được bỏ trống");
            } else {
                try {
                    int soLuong = Integer.parseInt(soLuongStr);
                    int thongSoKT = Integer.parseInt(thongSoKTStr);
                    
                    if (soLuong <= 0 || soLuong >= 31 || thongSoKT <= 0 || thongSoKT >= 31) {
                        JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải nằm trong khoảng từ 1 đến 30");
                    } else {
                        int row = tblCameraSau.getSelectedRow();
                        if (row == -1) {
                            JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng trong bảng để cập nhật");
                        } else {
                            CameraService.sua(getForm(), list.get(row).getId());
                            list = CameraService.getAllCameraSauTheoTuMoiDenCu(0);
                            showData(list);
                            txtSoluong.setText("");
                            txtThognsokithuat.setText("");
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải là số nguyên");
                }
            }
        }

    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            String soLuongStr = txtSoluong.getText().trim().trim();
            String thongSoKTStr = txtThognsokithuat.getText().trim().trim();
            
            if (soLuongStr.equals("") || thongSoKTStr.equals("")) {
                JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật không được bỏ trống");
            } else {
                try {
                    int soLuong = Integer.parseInt(soLuongStr);
                    int thongSoKT = Integer.parseInt(thongSoKTStr);
                    
                    if (soLuong <= 0 || soLuong >= 31 || thongSoKT <= 0 || thongSoKT >= 31) {
                        JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải nằm trong khoảng từ 1 đến 30");
                    } else {
                        CameraService.addCameraSau(getForm());
                        list = CameraService.getAllCameraSauTheoTuMoiDenCu(0);
                        showData(list);
                        txtSoluong.setText("");
                        txtThognsokithuat.setText("");
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Số lượng và thông số kỹ thuật phải là số nguyên");
                }
            }
        }
        

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCameraSau.getSelectedRow();
            CameraService.dungHoatDongCameraTheoID(list.get(row).getId()); 
            cbbTrangthai.setSelectedIndex(0);
            list = CameraService.getAllCameraSauTheoTuMoiDenCu(0);
            showData(list);
            txtSoluong.setText("");
            txtThognsokithuat.setText("");
            JOptionPane.showMessageDialog(this, "xóa  thành công");
            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnKhoiphucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiphucActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Khôi Phục ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCameraSau.getSelectedRow();
            CameraService.khoiPhucCameraTheoID(list.get(row).getId());         
            cbbTrangthai.setSelectedIndex(1);
            list = CameraService.getAllCameraSauTheoTuMoiDenCu(1);
            showData(list);
            txtSoluong.setText("");
            txtThognsokithuat.setText("");
            JOptionPane.showMessageDialog(this, "khôi phục  thành công");
        }        
    }//GEN-LAST:event_btnKhoiphucActionPerformed

    private void cbbTrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangthaiActionPerformed
        // TODO add your handling code here:
        int a = cbbTrangthai.getSelectedIndex();
        list = CameraService.getAllCameraSauTheoTuMoiDenCu(a);
        showData(list);        
        if (a == 0) {            
            list = CameraService.getAllCameraSauTheoTuMoiDenCu(0);            
            btnKhoiphuc.setEnabled(false);
            btnCapnhat.setEnabled(true);
            btnXoa.setEnabled(true);
            showData(list);            
            
        } else if (a == 1) {
            list = CameraService.getAllCameraSauTheoTuMoiDenCu(1);
            btnCapnhat.setEnabled(false);
            btnXoa.setEnabled(false);
            btnKhoiphuc.setEnabled(true);
            showData(list);
        }
    }//GEN-LAST:event_cbbTrangthaiActionPerformed

    private void tblCameraSauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCameraSauMouseClicked
        // TODO add your handling code here:
        int row = tblCameraSau.getSelectedRow();
        showIndex(row);
        
    }//GEN-LAST:event_tblCameraSauMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            int row = tblCameraSau.getSelectedRow();
            CameraService.deleteCamera(list.get(row).getId());
            list = CameraService.getAllCameraSau();
            showData(list);
            txtSoluong.setText("");
            txtThognsokithuat.setText("");
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraSauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraSauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraSauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraSauView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraSauView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnKhoiphuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTrangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCameraSau;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtThognsokithuat;
    // End of variables declaration//GEN-END:variables
}
