/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Dong;
import service.DongService;

/**
 *
 * @author Dell
 */
public class DongView extends javax.swing.JFrame {
   private List<Dong> list = new ArrayList<>();
    private DongService dongService = new DongService();
    private DefaultTableModel tableModel = new DefaultTableModel();
   
    /**
     * Creates new form formAnh
     */
    public DongView() {
        initComponents();
        
        tableModel = (DefaultTableModel) btlDong.getModel();
list = dongService.getAll1(0);
        showData(list);
        Updatetrangthai.setEnabled(false);
        btnKhoiPhuc.setEnabled(false);
        btnCapNhat.setEnabled(false);
    }
    private void showData(List<Dong> lists){
        tableModel.setRowCount(0);
        for (Dong bn : lists) {
            tableModel.addRow(new Object[]{bn.getId(),bn.getTen(),bn.getTrangthai()== 1 ? "Dừng hoạt động " : "Đang hoạt động"
                    });
        }
    }
     private Dong getForm(){
        Dong bn = new Dong(0, 0, txtDongMay.getText().trim().trim(), null, null);
        int trangThai=cbbTrangThai.getSelectedIndex();  
        return bn;
    }
      private void showIndex(int viTri){
        Dong bn = list.get(viTri);
       
        txtDongMay.setText(bn.getTen());
          int trangThai = bn.getTrangthai();
          if(trangThai == 1){
              cbbTrangThai.setSelectedIndex(0);
          }else{
              cbbTrangThai.setSelectedIndex(1);
          }
         
        
    }
      //----------PHÂN TRANG--------------
//      public void paging(int soTrang){
//        List<Dong> list = new ArrayList<>();
//        tableModel.setRowCount(0);               
//            for (int i = (soTrang-1)*5; i < soTrang * 5; i++) {
//                if(i < do.getAll().size()){
//                list.add(ss.getAll().get(i));
//                }
//            }                    
//        fillTable(list);        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNgaySua = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        btlDong = new javax.swing.JTable();
        cbotrangthai = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDongMay = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        Updatetrangthai = new javax.swing.JButton();
        btnKhoiPhuc = new javax.swing.JButton();

        jLabel9.setText("Màn hình");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel8.setText("Pin");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel10.setText("Cổng sạc");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("trạng Thái");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel16.setText("Sắp xếp");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel11.setText("Ghi chú");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Dòng Máy");

        txtNgaySua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySuaActionPerformed(evt);
            }
        });

        txtNgayTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTaoActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Chọn");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setText(">>");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel19.setText("1/10");

        jLabel20.setText("Trang");

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel2.setText("Dong MAY");

        txtTimKiem.setToolTipText("");
        txtTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseEntered(evt);
            }
        });

        jLabel15.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        cbbTrangThai.setBackground(new java.awt.Color(248, 243, 243));
        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Dừng hoạt động" }));

        jLabel12.setText("Trạng thái");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12)))); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btlDong.setBackground(new java.awt.Color(204, 204, 204));
        btlDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên Máy", "Trạng Thái"
            }
        ));
        btlDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btlDongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(btlDong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbotrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang hoạt động", "Dừng hoạt động" }));
        cbotrangthai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbotrangthaiMouseClicked(evt);
            }
        });
        cbotrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotrangthaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbotrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(cbotrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setText("Tên Dòng Máy");

        txtDongMay.setBackground(new java.awt.Color(238, 238, 238));
        txtDongMay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDongMayFocusLost(evt);
            }
        });
        txtDongMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDongMayActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("X");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        Updatetrangthai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Updatetrangthai.setText("Xóa");
        Updatetrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatetrangthaiActionPerformed(evt);
            }
        });

        btnKhoiPhuc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhoiPhuc.setText("KHÔI PHỤC");
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Updatetrangthai))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnKhoiPhuc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtDongMay, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDongMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(Updatetrangthai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKhoiPhuc)
                    .addComponent(btnXoa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        // TODO add your handling code here:
//        String ten = txtTimKiem.getText().trim().trim();
//        String id = txtTimKiem.getText().trim().trim();
////        list = dongService.timkiem(id, ten);
//        showData(list);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNgaySuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySuaActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txtDongMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDongMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDongMayActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:

int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn cập nhật ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
if (check == JOptionPane.YES_OPTION) {
    int row = btlDong.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một hàng trong bảng để cập nhật");
    } else {
        String dongMay = txtDongMay.getText().trim().trim().trim();
        
        if (dongMay.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên dòng máy không được bỏ trống");
        } else if (dongMay.length() > 25) {
            JOptionPane.showMessageDialog(this, "Tên dòng máy không được vượt quá 25 kí tự");
        } else if (!dongMay.matches("^[a-zA-Z0-9 ]*$")) {
            JOptionPane.showMessageDialog(this, "Tên dòng máy không hợp lệ. Hãy nhập tên dòng máy không chứa ký tự đặc biệt");
        } else {
            dongService.sua(getForm(), list.get(row).getId());
            list = dongService.getAll1(0);
            showData(list);
            txtDongMay.setText("");
            JOptionPane.showMessageDialog(this, "Cập nhật thành công");
            btnCapNhat.setEnabled(false);
            Updatetrangthai.setEnabled(false);
        }
    }
}

    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
   
        int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(check == JOptionPane.YES_OPTION){
               int row = btlDong.getSelectedRow();
       dongService.delete(list.get(row).getId());
        list = dongService.getAll1(0); 
        showData(list);
        
       JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtNgayTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTaoActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here
        
     //---------------lú luôn---------------
//int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
//if (check == JOptionPane.YES_OPTION) {
//    String dongMay = txtDongMay.getText().trim().trim().trim();
//    
//    if (dongMay.equals("")) {
//        JOptionPane.showMessageDialog(this, "Tên dòng máy không được bỏ trống");
//    } else if (!dongMay.matches("^[a-zA-Z]+[0-9]*[a-zA-Z]*$")) {
//        JOptionPane.showMessageDialog(this, "Tên dòng máy không hợp lệ. Hãy nhập tên dòng máy chứa ít nhất một chữ cái và không chứa kí tự đặc biệt, có thể có số đi kèm với chữ cái và không vượt quá 50 kí tự");
//    } else if (dongMay.length() > 50) {
//        JOptionPane.showMessageDialog(this, "Tên dòng máy không được vượt quá 50 kí tự");
//    } else {
//        dongService.add(getForm());
//        list = dongService.getAll1(0);
//        showData(list);
//        txtDongMay.setText("");
//        JOptionPane.showMessageDialog(this, "Thêm thành công");
//        btnCapNhat.setEnabled(false);
//        Updatetrangthai.setEnabled(false);
//    }
//}
int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thêm ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
if (check == JOptionPane.YES_OPTION) {
    String dongMay = txtDongMay.getText().trim().trim().trim();
    
    if (dongMay.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tên dòng máy không được bỏ trống");
    } else if (dongMay.length() > 25) {
        JOptionPane.showMessageDialog(this, "Tên dòng máy không được vượt quá 25 kí tự");
    } else if (!dongMay.matches("^[a-zA-Z0-9 ]*$")) {
        JOptionPane.showMessageDialog(this, "Tên dòng máy không hợp lệ. Hãy nhập tên dòng máy không chứa ký tự đặc biệt");
    } else {
        dongService.add(getForm());
        list = dongService.getAll1(0);
        showData(list);
        txtDongMay.setText("");
        JOptionPane.showMessageDialog(this, "Thêm thành công");
        btnCapNhat.setEnabled(false);
        Updatetrangthai.setEnabled(false);
    }
}



    }//GEN-LAST:event_btnThemActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btlDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btlDongMouseClicked
        // TODO add your handling code here:
        
         int row = btlDong.getSelectedRow();
        showIndex(row);
        String a = btlDong.getValueAt(row, 2).toString();
        if(a.equalsIgnoreCase("Đang hoạt động")){
            Updatetrangthai.setEnabled(true);
            btnKhoiPhuc.setEnabled(false);
        }else{
            Updatetrangthai.setEnabled(false);
            btnKhoiPhuc.setEnabled(true);
        }
if(row >= 0 && list.get(row).getTrangthai() ==0 ){
    btnCapNhat.setEnabled(true);
}else{
    btnCapNhat.setEnabled(false);
}

    }//GEN-LAST:event_btlDongMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtDongMay.setText("");
        txtID.setText("");
        txtNgaySua.setText("");
        txtNgayTao.setText("");
        txtTimKiem.setText("");
        cbbTrangThai.setSelectedIndex(0);
        list = dongService.getAll();
        showData(list);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDongMayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDongMayFocusLost
        // TODO add your handling code here:
//        String ten= txtDongMay.getText().trim().trim();
//        if(ten.length() >0){
//        }else{
//            JOptionPane.showConfirmDialog(rootPane, "tên dòng máy không để trống");
//        }
    }//GEN-LAST:event_txtDongMayFocusLost

    private void txtTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemMouseEntered

    private void UpdatetrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatetrangthaiActionPerformed
        // TODO add your handling code here:
         int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(check == JOptionPane.YES_OPTION){
        int row = btlDong.getSelectedRow();
        dongService.suatrangthai(getForm(), list.get(row).getId());

        cbotrangthai.setSelectedIndex(0);
               list = dongService.getAll1(0);
        showData(list);
         txtDongMay.setText("");
           JOptionPane.showMessageDialog(this, "xóa  thành công");
        Updatetrangthai.setEnabled(false);
        btnCapNhat.setEnabled(false);
        }
    }//GEN-LAST:event_UpdatetrangthaiActionPerformed

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        // TODO add your handling code here:
         int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Khôi Phục ? ", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if(check == JOptionPane.YES_OPTION){
        int row = btlDong.getSelectedRow();
        dongService.suatrangthai1(getForm(), list.get(row).getId());
    txtDongMay.setText("");
           JOptionPane.showMessageDialog(this, "khôi phục  thành công");       
        btnKhoiPhuc.setEnabled(false);
        cbotrangthai.setSelectedIndex(1);
             list = dongService.getAll1(1);
        showData(list);
        }
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void cbotrangthaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbotrangthaiMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbotrangthaiMouseClicked

    private void cbotrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotrangthaiActionPerformed
        // TODO add your handling code here:
        int a = cbotrangthai.getSelectedIndex();
        list = dongService.getAll1(a);
        showData(list);
      if(a<1){
            list = dongService.getAll1(0);
        showData(list);
        btnKhoiPhuc.setEnabled(false);
        }else if(a<2){
            list = dongService.getAll1(1);
        showData(list);
       
        btnKhoiPhuc.setEnabled(false);
        btnCapNhat.setEnabled(false   );
        Updatetrangthai.setEnabled(false);
        }
    }//GEN-LAST:event_cbotrangthaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DongView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatetrangthai;
    private javax.swing.JTable btlDong;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JComboBox<String> cbotrangthai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtDongMay;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNgaySua;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
